---
# tasks file for ansible-cloudflare-ddns
# - name: Install necessary packages
#   pacman:
#     name:
#       - dnsutils
#     state: latest

- name: Make sure /var/lib/cloudflare-ddns exists
  file:
    path: /var/lib/cloudflare-ddns
    state: directory
    owner: root
    group: root

- name: Write update.sh to /var/lib/cloudflare-ddns/update.sh
  template:
    src: update.sh.j2
    dest: /var/lib/cloudflare-ddns/update.sh
    owner: root
    group: root
    mode: '0755'

- name: "Template cloudflare.service to /etc/systemd/system/cloudflare.service"
  template:
    src: "cloudflare.service.j2"
    dest: "/etc/systemd/system/cloudflare.service"
    mode: '0644'


- name: "Template cloudflare.timer to /etc/systemd/system/cloudflare.timer"
  template:
    src: "cloudflare.timer.j2"
    dest: "/etc/systemd/system/cloudflare.timer"
    mode: '0644'

- name: "Enable cloudflare.timer on startup"
  systemd:
    name: "cloudflare.timer"
    enabled: yes
    daemon_reload: yes
    state: restarted
    masked: no
